databases:
  - name: events
    databaseName: events_vzco
    user: events_vzco_user

services:
  - type: web
    name: lambistic-events
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: events
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false